### ISSUE TITLE
Property mismatch: files or item_urls

### ISSUE THREAD

**Issue by ricardo-lewis** [fetchapp/fetchapp-php-2.0#14]
The Product->create() function uses the **files** property, 

https://github.com/fetchapp/fetchapp-php-2.0/blob/0e1ef8d6bbf855445afda9a3e4a2801c446683d5/src/FetchApp/API/Product.php#L259

However the toXML function uses the **item_urls** property:
https://github.com/fetchapp/fetchapp-php-2.0/blob/0e1ef8d6bbf855445afda9a3e4a2801c446683d5/src/FetchApp/API/Product.php#L426

So I get
`Warning: Invalid argument supplied for foreach() on line 426`

**Comment by conantp** [comment]
Hey @ricardo-lewis - I just deployed an update that should clear up this issue, if you're still using this library. 

Please let me know if you have any further questions. 

Patrick Conant
